import fs from 'fs-extra';
import yaml from 'js-yaml';
import path from 'path';
import {
  Agent,
  DEFAULT_WORKFLOWS,
  SUPPORTED_AGENTS,
  SUPPORTED_FRAMEWORKS,
} from '../constants';
import { RegistryMetadata } from '../models/types';
import { ConfigService } from './ConfigService';
import { DetectionService } from './DetectionService';

/**
 * Contextual data gathered during project discovery to inform the initialization prompt.
 */
export interface InitContext {
  /** Map of framework IDs and whether they were detected in the workspace */
  frameworkDetection: Record<string, boolean>;
  /** Map of agent IDs and whether they were detected in the workspace */
  agentDetection: Record<string, boolean>;
}
/**
 * User responses gathered from the initialization prompt.
 */
export interface InitAnswers {
  /** The primary framework ID chosen by the user */
  framework: string;
  /** List of AI agents to enable for the project */
  agents: Agent[];
  /** The URL of the skill registry to use */
  registry: string;
}

/**
 * Service for orchestrating the project initialization process.
 * Handles environment discovery, prompt choice generation, and initial config creation.
 */
export class InitService {
  private detectionService = new DetectionService();
  private configService = new ConfigService();

  /**
   * Performs environmental discovery to identify existing frameworks and agents.
   * @returns An InitContext containing detection results
   */
  async getInitializationContext(): Promise<InitContext> {
    const [frameworkDetection, agentDetection] = await Promise.all([
      this.detectionService.detectFrameworks(),
      this.detectionService.detectAgents(),
    ]);

    return { frameworkDetection, agentDetection };
  }

  /**
   * Transforms the initialization context and registry metadata into choices for the interactive prompt.
   * @param context The discovered initialization context
   * @param supportedCategories List of categories currently supported by the registry
   * @returns Formatted choices and the default framework ID
   */
  getPromptChoices(context: InitContext, supportedCategories: string[]) {
    const frameworkChoices = SUPPORTED_FRAMEWORKS.map((f) => ({
      name: supportedCategories.includes(f.id)
        ? f.name
        : `${f.name} (Coming Soon)`,
      value: f.id,
    }));

    const agentChoices = SUPPORTED_AGENTS.map((a) => ({
      name: `${a.name} (${a.path}/)`,
      value: a.id,
      checked: context.agentDetection[a.id] ?? false,
    }));

    const defaultFramework =
      SUPPORTED_FRAMEWORKS.find((f) => context.frameworkDetection[f.id])?.id ||
      'flutter';

    return {
      frameworkChoices,
      agentChoices,
      defaultFramework,
    };
  }

  /**
   * Orchestrates the construction, validation, and saving of the initial `.skillsrc` configuration.
   * @param answers The user's prompt responses
   * @param metadata Registry metadata for versioning
   * @param cwd Current working directory
   */
  async buildAndSaveConfig(
    answers: InitAnswers,
    metadata: Partial<RegistryMetadata>,
    cwd: string = process.cwd(),
  ) {
    const frameworkId = answers.framework;
    const frameworkDef = SUPPORTED_FRAMEWORKS.find((f) => f.id === frameworkId);

    const languages = frameworkDef
      ? await this.detectionService.detectLanguages(frameworkDef)
      : [];

    const includeWorkflows = answers.agents.includes(Agent.Antigravity);

    const config = this.configService.buildInitialConfig(
      frameworkId,
      answers.agents,
      answers.registry,
      metadata,
      languages,
      includeWorkflows ? DEFAULT_WORKFLOWS : [],
    );

    const projectDeps = await this.detectionService.getProjectDeps();
    this.configService.applyDependencyExclusions(config, projectDeps);
    this.configService.reconcileDependencies(config, projectDeps);

    const commentHeader = `# Auto-detected configuration generated by full-stack-skill init\r
#\r
# Presence in 'skills' list = Active. To disable a skill, remove it from the list.\r
# 'exclude': IDs of sub-skills to skip during sync (auto-populated with undetected skills).\r
# 'custom_overrides': IDs of skills to PROTECT. Use this if you have modified a standard \r
# skill locally and don't want the CLI to overwrite it.\r
#\r
# Run 'fss list-skills' to view all available skills.\r
#
# TIP: For Jira/Zephyr automation and requirement analysis, manually add:
# skills:
#   quality-engineering: { ref: quality-engineering-v1.0.0 }
#
`;
    const configPath = path.join(cwd, '.skillsrc');
    await fs.outputFile(configPath, commentHeader + yaml.dump(config));
  }
}
